spring:
  application:
    name: Config-Default



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

user-service:
  database:
    name: testDb
    password: root

service:
  user-service:
    name: USER-SERVICE
  order-service:
    name: ORDER-SERVICE
  takenote-service:
    name: TAKENOTE-SERVICE
  payment-service:
    name: PAYMENTSERVICE
